name: Deploy on GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Yarn install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Yarn build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build:prod
    - name: Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
